### ISSUE TITLE
Add additional graph return types

### ISSUE THREAD

**Issue by JaneClelandHuang** [JamieDixon/GraphViz-C-Sharp-Wrapper#4]
It would be really helpful if you could add additional types to the Enums.GraphReturnType.  Currently it supports pdf, jpg, and png.  GraphViz supports many additional output formats.  In particularly - I'm looking for "plain" and "plain-ext" which output node positions, arc coordinates etc.  

I'd like to use GraphViz' layout capability - to generate coordinates and then redraw the graph within C# so that I can make it more interactive.

btw great solution!  It all worked very easily..  Thanks!

**Comment by JamieDixon** [comment]
Thanks for raising this issue, Jane.

I've added enum values for plain and plain-ext. The output of `GenerateGraph` is always a `byte[]` so you'll need to convert this back into a string before use.

In my tests I'm using `System.Text.Encoding.Default.GetString(output)` where `output` is a `byte[]`.
