### ISSUE TITLE
Allow configurable GraphViz command line tool's location

### ISSUE THREAD

**Issue by toannguyen83** [JamieDixon/GraphViz-C-Sharp-Wrapper#6]
Hello,
Right now the GraphViz wrapper is looking at the GraphViz command line tool from the same location of the GraphVizWrapper.dll. It will be nice to have the GraphViz command tool's location configurable. For example, I can have the command line tool stored in C:\Program Files\GraphViz, and the web app from IIS knows where to execute the tool instead of copying the tool in the web app \bin folder. 

We have application deployment system that will deploy each release in a new folder. It seems costly to duplicate the graphviz command line tool on each deploy. So it's better to have graphviz command line stored in a static location, then just have the app pointing to the static location. 

Thanks!

Toan

**Comment by JamieDixon** [comment]
This has been fixed by this pull request: https://github.com/JamieDixon/GraphViz-C-Sharp-Wrapper/commit/e93235ab2566c47bf1d6ffdbffbaff16bf5673a1
